# Week 12
## Loading Data

In [3]:
import pandas as pd

In [4]:
shootings_df = pd.read_csv('../Data/Shootings_(2006-Present)_20260401.csv')              # loading three dataset files
offenders_df = pd.read_csv('../Data/Shooting_Offenders_(2006-Present)_20260401.csv')
victims_df = pd.read_csv('../Data/Shooting_Victims_(2006-Present)_20260401.csv')

In [5]:
combined_df = pd.merge(shootings_df, offenders_df, on='INCIDENT_KEY', how='inner')             # merging the datasets to a combined dataset
combined_df = pd.merge(combined_df, victims_df, on='INCIDENT_KEY', how='inner')

## Exploration

In [21]:
combined_df.head(10)

,INCIDENT_KEY,OCCUR_DATE,OCCUR_TIME,BORO,LOC_OF_OCCUR_DESC,PRECINCT,JURISDICTION_CODE,LOC_CLASSFCTN_DESC,LOCATION_DESC,X_COORD_CD,...,Longitude,PERP_ID,PERP_AGE_GROUP,PERP_SEX,PERP_RACE,VICTIM_ID,VICTIM_AGE_GROUP,VICTIM_SEX,VICTIM_RACE,STAT_MURDER_FLG
0,297623042,12/06/2024,13:06:00,MANHATTAN,OUTSIDE,1,0.0,STREET,NaN,983437,...,-74.002931,297623042-1,25-44,MALE,BLACK,297623042-1,18-24,MALE,BLACK HISPANIC,N
1,242784290,03/28/2022,22:18:00,MANHATTAN,OUTSIDE,5,0.0,STREET,MULTI DWELL - APT BUILD,984732,...,-73.998260,242784290-1,18-24,MALE,BLACK,242784290-1,18-24,MALE,BLACK,N
2,24449553,09/23/2006,00:02:00,MANHATTAN,OUTSIDE,5,0.0,STREET,NaN,986929,...,-73.990335,24449553-11107,<18,MALE,BLACK HISPANIC,24449553-10091,<18,MALE,BLACK HISPANIC,N
3,64318199,08/02/2009,01:44:00,MANHATTAN,OUTSIDE,5,2.0,HOUSING,MULTI DWELL - PUBLIC HOUS,986577,...,-73.991606,64318199-17240,18-24,MALE,BLACK,64318199-16625,25-44,MALE,BLACK HISPANIC,N
4,64318199,08/02/2009,01:44:00,MANHATTAN,OUTSIDE,5,2.0,HOUSING,MULTI DWELL - PUBLIC HOUS,986577,...,-73.991606,64318199-17554,<18,MALE,BLACK,64318199-16625,25-44,MALE,BLACK HISPANIC,N
5,64318199,08/02/2009,01:44:00,MANHATTAN,OUTSIDE,5,2.0,HOUSING,MULTI DWELL - PUBLIC HOUS,986577,...,-73.991606,64318199-17555,18-24,MALE,BLACK,64318199-16625,25-44,MALE,BLACK HISPANIC,N
6,11118235,04/26/2006,21:05:00,MANHATTAN,OUTSIDE,6,0.0,STREET,NaN,982301,...,-74.007033,11118235-9762,UNKNOWN,UNKNOWN,UNKNOWN,11118235-8740,25-44,MALE,BLACK,N
7,52144006,10/10/2008,01:38:00,MANHATTAN,OUTSIDE,7,2.0,HOUSING,MULTI DWELL - PUBLIC HOUS,989248,...,-73.981970,52144006-15639,UNKNOWN,UNKNOWN,UNKNOWN,52144006-14943,18-24,MALE,WHITE HISPANIC,N
8,37401695,01/01/2008,05:12:00,MANHATTAN,OUTSIDE,7,2.0,HOUSING,MULTI DWELL - PUBLIC HOUS,989138,...,-73.982369,37401695-15943,UNKNOWN,UNKNOWN,UNKNOWN,37401695-13081,18-24,MALE,WHITE HISPANIC,N
9,16631507,05/31/2006,21:16:00,MANHATTAN,OUTSIDE,7,2.0,HOUSING,MULTI DWELL - APT BUILD,989248,...,-73.981970,16631507-10030,UNKNOWN,UNKNOWN,UNKNOWN,16631507-8972,<18,MALE,WHITE HISPANIC,N

In [22]:
shootings_df.head(10)

,INCIDENT_KEY,OCCUR_DATE,OCCUR_TIME,BORO,LOC_OF_OCCUR_DESC,PRECINCT,JURISDICTION_CODE,LOC_CLASSFCTN_DESC,LOCATION_DESC,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
0,297623042,12/06/2024,13:06:00,MANHATTAN,OUTSIDE,1,0.0,STREET,NaN,983437,201643,40.720149,-74.002931
1,73794477,07/21/2010,01:32:00,MANHATTAN,OUTSIDE,1,0.0,STREET,BAR/NIGHT CLUB,982761,204594,40.728241,-74.005370
2,242784290,03/28/2022,22:18:00,MANHATTAN,OUTSIDE,5,0.0,STREET,MULTI DWELL - APT BUILD,984732,200728,40.717629,-73.998260
3,24449553,09/23/2006,00:02:00,MANHATTAN,OUTSIDE,5,0.0,STREET,NaN,986929,202081,40.721343,-73.990335
4,64318199,08/02/2009,01:44:00,MANHATTAN,OUTSIDE,5,2.0,HOUSING,MULTI DWELL - PUBLIC HOUS,986577,200423,40.716801,-73.991606
5,11118235,04/26/2006,21:05:00,MANHATTAN,OUTSIDE,6,0.0,STREET,NaN,982301,204919,40.729142,-74.007033
6,235033374,10/15/2021,20:30:00,MANHATTAN,OUTSIDE,7,0.0,STREET,NaN,987969,200865,40.718004,-73.986584
7,52144006,10/10/2008,01:38:00,MANHATTAN,OUTSIDE,7,2.0,HOUSING,MULTI DWELL - PUBLIC HOUS,989248,198472,40.711446,-73.981970
8,37401695,01/01/2008,05:12:00,MANHATTAN,OUTSIDE,7,2.0,HOUSING,MULTI DWELL - PUBLIC HOUS,989138,199179,40.713385,-73.982369
9,16631507,05/31/2006,21:16:00,MANHATTAN,OUTSIDE,7,2.0,HOUSING,MULTI DWELL - APT BUILD,989248,198472,40.711446,-73.981970

In [23]:
offenders_df.head(10)

   INCIDENT_KEY        PERP_ID PERP_AGE_GROUP PERP_SEX       PERP_RACE
0       9953248   9953248-9042          18-24     MALE           BLACK
1      10137418  10137418-9127          25-44     MALE           BLACK
2      10137428  10137428-9147        UNKNOWN  UNKNOWN         UNKNOWN
3      10187494  10187494-9181        UNKNOWN     MALE           BLACK
4      10187494  10187494-9195        UNKNOWN     MALE           BLACK
5      10187496  10187496-9184          18-24     MALE  WHITE HISPANIC
6      10187501  10187501-9189            <18     MALE           BLACK
7      10187502  10187502-9190          25-44     MALE           BLACK
8      10187517  10187517-9212          25-44     MALE           BLACK
9      10240242  10240242-9227          18-24     MALE  WHITE HISPANIC

In [24]:
victims_df.head(10)

,INCIDENT_KEY,VICTIM_ID,VICTIM_AGE_GROUP,VICTIM_SEX,VICTIM_RACE,STAT_MURDER_FLG
0,299453927,299453927-1,25-44,MALE,BLACK,N
1,212336415,212336415-1,18-24,MALE,BLACK,N
2,280768895,280768895-1,25-44,MALE,BLACK,N
3,141824677,141824677-27687,25-44,MALE,BLACK HISPANIC,N
4,270079203,270079203-1,45-64,MALE,BLACK,Y
5,138882700,138882700-26963,25-44,MALE,BLACK,N
6,138882700,138882700-26964,45-64,MALE,BLACK,N
7,289881880,289881880-1,25-44,MALE,WHITE HISPANIC,N
8,305930898,305930898-1,25-44,MALE,BLACK,N
9,138899428,138899428-26973,18-24,MALE,BLACK,N

In [25]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23094 entries, 0 to 23093
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   INCIDENT_KEY        23094 non-null  int64
 1   OCCUR_DATE          23094 non-null  object
 2   OCCUR_TIME          23094 non-null  object
 3   BORO                23094 non-null  object
 4   LOC_OF_OCCUR_DESC   23094 non-null  object
 5   PRECINCT            23094 non-null  int64
 6   JURISDICTION_CODE   23092 non-null  float64
 7   LOC_CLASSFCTN_DESC  23070 non-null  object
 8   LOCATION_DESC       9942 non-null   object
 9   X_COORD_CD          23094 non-null  int64
 10  Y_COORD_CD          23094 non-null  int64
 11  Latitude            22961 non-null  float64
 12  Longitude           22961 non-null  float64
 13  PERP_ID             23094 non-null  object
 14  PERP_AGE_GROUP      23059 non-null  object
 15  PERP_SEX            23094 non-null  object
 16  PERP_RACE           23094 non-null  object
 17  VICTIM_ID           23094 non-null  object
 18  VICTIM_AGE_GROUP    23094 non-null  object
 19  VICTIM_SEX          23094 non-null  object
 20  VICTIM_RACE         23094 non-null  object
 21  STAT_MURDER_FLG     23094 non-null  object
dtypes: float64(3), int64(4), object(15)
memory usage: 3.9+ MB

In [26]:
combined_df.describe()

,INCIDENT_KEY,PRECINCT,JURISDICTION_CODE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
count,2.309400e+04,23094.000000,23092.000000,2.309400e+04,23094.000000,22961.000000,22961.000000
mean,1.289751e+08,64.976054,0.297852,1.009250e+06,209830.635187,40.676862,-73.790723
std,9.073286e+07,28.631070,0.708999,1.913059e+04,32168.114337,1.636608,2.965408
min,9.953245e+06,1.000000,0.000000,9.148030e+05,125922.000000,0.000000,-74.249755
25%,5.174576e+07,43.000000,0.000000,9.998750e+05,183332.000000,40.669559,-73.943512
50%,8.786904e+07,67.000000,0.000000,1.007951e+06,198430.000000,40.710904,-73.914367
75%,2.157763e+08,81.000000,0.000000,1.017276e+06,240878.000000,40.827736,-73.880561
max,3.182339e+08,123.000000,2.000000,1.065473e+06,271127.000000,40.910810,0.000000

In [27]:
print('Shape of Combined Dataset: ',combined_df.shape)
print('Shape of Combined Dataset: ',shootings_df.shape)
print('Shape of Combined Dataset: ',offenders_df.shape)
print('Shape of Combined Dataset: ',victims_df.shape)

Shape of Combined Dataset:  (23094, 22)
Shape of Combined Dataset:  (23988, 13)
Shape of Combined Dataset:  (18750, 5)
Shape of Combined Dataset:  (28748, 6)